version: "3.7"
name: backloggd-discord

services:
  bot:
    image: backloggd-discord:latest
    env_file: ".bot.env"
    restart: always
    volumes:
    - db:/var/lib/backloggd-discord
    secrets:
    - discord_token
    - otlp_token

volumes:
  db:
secrets:
  discord_token:
    external: true
  otlp_token:
    external: true
