FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y sqlite3 wget && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/benbjohnson/litestream/releases/download/v0.3.13/litestream-v0.3.13-linux-amd64.deb
RUN dpkg -i litestream-v0.3.13-linux-amd64.deb
CMD [""]

